### ISSUE TITLE
老哥怎么没有数据库文件  能不能上传一下啊 谢谢啦

### ISSUE THREAD

**Issue by 121516471** [Cool-Coding/angular-springboot-demo#1]
老哥怎么没有数据库文件  能不能上传一下啊 谢谢啦

**Comment by Cool-Coding** [comment]
数据库表是ORM框架自动生成的，配置好数据库就行了

**Comment by Cool-Coding** [comment]
[hotel.sql.zip](https://github.com/Cool-Coding/angular-springboot-demo/files/3078264/hotel.sql.zip)
