### ISSUE TITLE
在线演示功能好像使用不了，方便担供一下在线演示或本地部署操作手册吗？

### ISSUE THREAD

**Issue by Justin168562** [Cool-Coding/angular-springboot-demo#3]
在线演示功能好像使用不了，方便担供一下在线演示或本地部署操作手册吗？

**Comment by XIAAMAN** [comment]
有没有数据库文件啊，可以提供一下么

**Comment by Cool-Coding** [comment]
@XIAAMAN #2

**Comment by Cool-Coding** [comment]
@Justin168562 购买的vps空间不够了,不提供演示了；
本地也很方便运行。hotel-front/hotel-server是两个springboot项目，使用intellij idea分别导入即可。
给你一个参考连接：[IntelliJ IDEA 导入 maven项目](https://blog.csdn.net/huhuhuemail/article/details/76614036)
