### ISSUE TITLE
您好，这个项目没有写完是吗？

### ISSUE THREAD

**Issue by SouthWind0** [Cool-Coding/angular-springboot-demo#4]
我看这个项目，打开之后，很多地方报错，想问下您情况。

**Comment by Cool-Coding** [comment]
@SouthWind0 项目完成了，可以正常运行；后期可能会增加一些新功能。可能是您执行环境错误了，
这个项目是前后端分离的，前端使用webStorm，后端使用intellij Idea开发的，你分别导入再运行。

**Comment by SouthWind0** [comment]
能否添加QQ？我就是分别运行，可是我看java代码很多业务处理都是空的，麻烦大哥确认下java代码是否完整??另外缺少数据库，麻烦大哥提供一下，不胜感激。

**Comment by SouthWind0** [comment]
导入之后Controller里面很多错误，大佬
